on:
  rss:
    url: https://feeds.feedburner.com/cnadeutsche/nachrichten
    config:
      limit: 1
jobs:
  tgram:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on 1000plus
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{on.rss.outputs.contentSnippet}}
              
              ${{on.rss.outputs.link}}
