on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: CNAdeutsch
      exclude_replies: true
      include_rts: false
    config:
      active: true
      every: "30 */4 * * *"
      filter:
        full_text:
          $regex: ....+
jobs:
  post2tumblr:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/ifttt-webhook-action@v1
        with:
          event: post2tumblr
          key: ${{ secrets.TUMBLR_WEBHOOK_KEY }}
          value1: ${{ on.twitter.outputs.full_text }}
          value2: "${{ on.twitter.outputs.full_text }}"
          value3: "Catholic News Agency Deutsch"
