on:
  rss:
    url: https://feeds.feedburner.com/cnadeutsche/nachrichten
    config:
      every: "* * * * *"
      limit: 1
      format: |
        item.content = item.content.replace(/<style([\s\S]*?)<\/style>/gi, '').replace(/<script([\s\S]*?)<\/script>/gi, '').replace(/<\/div>/ig, '').replace(/<\/li>/ig, '').replace(/<li>/ig, '').replace(/<\/ul>/ig, '').replace(/<\/p>/ig, '').replace(/<br\s*[\/]?>/gi, '').replace(/<[^>]+>/ig, '').replace(/<\/*code>/ig, '').replace(/<\/*textarea.*>/ig, '').replace(/<\/*samp.*>/ig, '').replace(/<\/*pre.*>/ig, '').replace(/"/ig, '&quot;').substr(0, 400)
        return item;
jobs:
  fediverse-mastodon:
    name: send2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: 'Call fediverse'
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN_VANEWS }}
          message: "<<<${{on.rss.outputs.content}}>>> ${{on.rss.outputs.link}}"
          host: "muenchen.social" # If not using default "mastodon.social"
      - run: echo ${{ on.rss.outputs.title }}
      - run: echo ${{ on.rss.outputs.content }}
      - run: echo ${{ on.rss.outputs.link }}
