on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: CNAdeutsch
      exclude_replies: true
      include_rts: true
    config:
      active: true
      every: "0 */4 * * *"
      limit: 1
      filter:
        full_text:
          $regex: ....+
        created_at:
          $regex: ....+
jobs:
  cna2friendica:
    name: 'Post CNA to Friendica'
    runs-on: ubuntu-latest
    steps:
      - name: 'Call friendica API'
        uses: actionsflow/axios@v1
        with:
          url: https://libranet.de/api/statuses/update.json
          method: 'POST'
          accept: 200,201,204,429
          headers: '{ "Content-Type": "application/json" }'
          data: '{ "source": "Twitter",  "title": "${{ on.twitter.outputs.user.name }",  "status": "${{ on.twitter.outputs.full_text }} https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}" }'
          params: '{ "source": "Twitter",  "title": "${{ on.twitter.outputs.user.name }",  "status": "${{ on.twitter.outputs.full_text }} https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}" }'
          timeout: 10000
          basic-auth: ${{ secrets.friendica_auth_username }}:${{ secrets.friendica_auth_password }}
          is_debug: true
      - run: echo ${{ steps.api.outputs.status }}
      - run: echo ${{ steps.api.outputs.data }}
      - run: echo ${{ steps.api.outputs.headers }}
