on:
  rss:
    url: https://feeds.feedburner.com/cnadeutsche/nachrichten
    config:
      every: "30 */4 * * *"
      limit: 1
jobs:
  fediverse-mastodon:
    name: send2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: 'Call fediverse'
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN_VANEWS }}
          message: |
              ${{on.rss.outputs.title}}
              ${{on.rss.outputs.link}}
          host: "muenchen.social" # If not using default "mastodon.social"
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          content: ${{on.rss.outputs.content}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo content: $content
          echo link: $link
