on:
  rss:
    url:
#      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-nl.xml
    config:
      every: "0 8 * * *"
      filter:
        content:
          $regex: ....+
#         categories:
#           $not:
#             $regex: MEDITATIO
jobs:
  maildraft2nuntii:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Send draft mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{secrets.EMAIL_SERVER_ADDRESS}}
          server_port: ${{secrets.EMAIL_SERVER_PORT}}
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: ${{on.rss.outputs.title}}
          body: |
            ${{on.rss.outputs.content}}
          # Read file contents as body:
          to: ${{secrets.EMAIL_TO_NUNTII_DRAFT}}
          from: ${{secrets.EMAIL_FROM}}
          # Optional content type (defaults to text/plain):
          content_type: text/html