on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-pl.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-pl.xml
    config:
      every: "30 4 * * *"
      filter:
        content:
          $regex: ....+
jobs:
  pipe2nuntii:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.NUNTII_PIPE_URL }}
          method: POST
          body: |
            {
              "title": "<<<${{ on.rss.outputs.title }}>>>",
              "content": "<<<${{ on.rss.outputs.content }}>>>",
              "category": "po polsku"
            }
