on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "30 8 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: EVANGELIUM
jobs:
  evangelium2friendica:
    name: 'Post Evangelium to Friendica'
    runs-on: ubuntu-latest
    steps:
      - name: Get textstelle
        id: kapitel
        run: echo "::set-output name=stelle::"$(echo "${{on.rss.outputs.title}}" | awk -F" " '{print $NF}')
      - name: Get evangelist
        id: evangelist
        run: |
          if [[ "${{on.rss.outputs.title}}" == *"Johannes"* ]]
          then
            echo "::set-output name=name::Johannes"
          elif [[ "${{on.rss.outputs.title}}" == *"Lukas"* ]]
          then
            echo "::set-output name=name::Lukas"
          elif [[ "${{on.rss.outputs.title}}" == *"Matthäus"* ]]
          then
            echo "::set-output name=name::Matthäus"
          elif [[ "${{on.rss.outputs.title}}" == *"Markus"* ]]
          then
            echo "::set-output name=name::Markus"
          else
            echo "::set-output name=name::unbekannt"
          fi
      - name: Get link
        id: link
        run: echo "::set-output name=url::https://www.bibleserver.com/EU/${{steps.evangelist.outputs.name}}${{steps.kapitel.outputs.stelle}}"
      - name: 'Call friendica API'
        uses: actionsflow/axios@v1
        with:
          url: https://libranet.de/api/statuses/update.json
          method: 'POST'
          accept: 200,201,204,429
          headers: '{ "Content-Type": "application/json" }'
          data: '{ "source": "ETfT",  "title": "<<<${{on.rss.outputs.title}}>>>",  "htmlstatus": "<b><a href =\"${{steps.link.outputs.url}}\"><<<${{on.rss.outputs.title}}>>></a></b>:<b><br></b><<<${{on.rss.outputs.content}}>>><b><br></b><i><a href=\"${{on.rss.outputs.link}}\"><<<${{on.rss.outputs.link}}>>></a></i>" }'
          params: '{ "source": "ETfT",  "title": "<<<${{on.rss.outputs.title}}>>>",  "htmlstatus": "<b><a href =\"${{steps.link.outputs.url}}\"><<<${{on.rss.outputs.title}}>>></a></b>:<b><br></b><<<${{on.rss.outputs.content}}>>><b><br></b><i><a href=\"${{on.rss.outputs.link}}\"><<<${{on.rss.outputs.link}}>>></a></i>" }'
          timeout: 60000
          basic-auth: ${{ secrets.friendica_auth_username }}:${{ secrets.friendica_auth_password }}
          is_debug: true
      - run: echo ${{ steps.api.outputs.status }}
      - run: echo ${{ steps.api.outputs.data }}
      - run: echo ${{ steps.api.outputs.headers }}
