on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "30 9,13 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: EVANGELIUM
jobs:
  tgram:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Get textstelle
        id: kapitel
        run: echo "::set-output name=stelle::"$(echo "${{on.rss.outputs.title}}" | awk -F" " '{print $NF}')
      - name: Get evangelist
        id: evangelist
        run: |
          if [[ "${{on.rss.outputs.title}}" == *"Johannes"* ]]
          then
            echo "::set-output name=name::Johannes"
          elif [[ "${{on.rss.outputs.title}}" == *"Lukas"* ]]
          then
            echo "::set-output name=name::Lukas"
          elif [[ "${{on.rss.outputs.title}}" == *"Matthäus"* ]]
          then
            echo "::set-output name=name::Matthäus"
          elif [[ "${{on.rss.outputs.title}}" == *"Markus"* ]]
          then
            echo "::set-output name=name::Markus"
          else
            echo "::set-output name=name::unbekannt"
          fi
      - name: Get link
        id: link
        run: echo "::set-output name=url::https://www.bibleserver.com/EU/${{steps.evangelist.outputs.name}}${{steps.kapitel.outputs.stelle}}"
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{on.rss.outputs.title}}:
              
              ${{on.rss.outputs.content}}
              
              ${{steps.link.outputs.url}}
              
