on:
  rss:
    url: http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      active: false
      every: "0 10 * * *"
      filter:
        content:
          $regex: ....+
        title:
          $regex: Kommentar
jobs:
  kommentar2slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C02KYC1L5GD\", \"blocks\": [{\"type\": \"section\",\"text\": {\"type\": \"mrkdwn\",\"text\": \"*${{on.rss.outputs.title}}*\\n${{on.rss.outputs.content}}\\n<${{on.rss.outputs.link}}>\"}}]}'
