on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "0 10,14 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: MEDITATIO
jobs:
  tgram:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{on.rss.outputs.title}}:
              
              ${{on.rss.outputs.content}}
              
              ${{on.rss.outputs.link}}
              
