on:
  rss:
    url:
      - https://www.alfa-ev.de/feed/
      - https://www.bundesverband-lebensrecht.de/feed/
      - https://righttolife.org.uk/feed
    config:
      active: true
      filter:
        content:
          $regex: ....+
        title:
          $regex: ....+
        link:
          $regex: ....+
jobs:
  post2tumblr:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/ifttt-webhook-action@v1
        with:
          event: post2tumblr
          key: ${{ secrets.TUMBLR_WEBHOOK_KEY }}
          value1: ${{ on.rss.outputs.title }}
          value2: "${{ on.rss.outputs.content }} </br> ${{on.rss.outputs.link}}"
          value3: "Lebensrecht für Alle"
