on:
  rss:
    url: http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "0 7 * * *"
      filter:
        content:
          $regex: ....+
        title:
          $not:
            $regex: (Evangelium|Kommentar|Psalm)
jobs:
  lectio2discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_TAGESEVANGELIUM }}
#          DISCORD_EMBEDS: {"embeds": [{"title": "${{on.rss.outputs.title}}", "url": "${{on.rss.outputs.link}}", "description": "${{on.rss.outputs.content}}"}]}
        uses: Ilshidur/action-discord@master
        with:
          args: '**__${{on.rss.outputs.title}}__**: ${{on.rss.outputs.content}} *(${{on.rss.outputs.link}})*'
