on:
  rss:
    url: http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "0 7 * * *"
      filter:
        content:
          $regex: ....+
        title:
          $not:
            $regex: (Evangelium|Kommentar|Psalm)
jobs:
  send2matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: |
              ${{on.rss.outputs.title}}:
              
              ${{on.rss.outputs.content}}
              
              ${{on.rss.outputs.link}}
              
         server: "synod.im"
