on:
  twitter:
    config:
      every: "0 6 * * *"
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: losung
      exclude_replies: true,
      include_rts: false,
jobs:
  send2matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "${{ on.twitter.outputs.full_text }}"
         server: "synod.im"
  fediverse-mastodon:
    name: send2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: 'Call fediverse'
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          message: "${{ on.twitter.outputs.full_text }}"
          host: "muenchen.social" # If not using default "mastodon.social"
