on:
  twitter:
    api: statuses/user_timeline
    config:
      active: true
      every: "0 8 * * *"
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: Pontifex_de
      exclude_replies: true,
      include_rts: false,
jobs:
  tgram:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on 1000plus
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              Franziskus I:
              
              ${{ on.twitter.outputs.full_text }}
              
              https://twitter.com/${{ on.twitter.outputs.user.screen_name }}/status/${{ on.twitter.outputs.id_str }}
