on:
  twitter:
    api: statuses/user_timeline
    config:
      active: false
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: Pontifex_de
      exclude_replies: true,
      include_rts: false,
jobs:
  fediverse-mastodon:
    name: send2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: 'Call fediverse'
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          message: "Franziskus I: ${{ on.twitter.outputs.full_text }}"
          host: "muenchen.social" # If not using default "mastodon.social"
