on:
  twitter:
    api: statuses/user_timeline
    config:
      active: true
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: Pontifex_de
      exclude_replies: true,
      include_rts: false,
jobs:
  pontifexde2friendica:
    name: 'Post pontifex_de to Friendica'
    runs-on: ubuntu-latest
    steps:
      - name: 'Call friendica API'
        uses: actionsflow/axios@v1
        with:
          url: https://libranet.de/api/statuses/update.json
          method: 'POST'
          accept: 200,201,204,429
          headers: '{ "Content-Type": "application/json" }'
          data: '{ "source": "Twitter",  "title": "Papst Franziskus I.",  "htmlstatus": "Franziskus I: <<<${{ on.twitter.outputs.full_text }}>>><b><br><\/b><p><i><a href=\"https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}\">https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}</a></i><\/p>" }'
          params: '{ "source": "Twitter",  "title": "Papst Franziskus I.",  "htmlstatus": "Franziskus I: <<<${{ on.twitter.outputs.full_text }}>>><b><br><\/b><p><i><a href=\"https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}\">https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}</a></i><\/p>" }'
          timeout: 10000
          basic-auth: ${{ secrets.friendica_auth_username }}:${{ secrets.friendica_auth_password }}
          is_debug: true
      - run: echo ${{ steps.api.outputs.status }}
      - run: echo ${{ steps.api.outputs.data }}
      - run: echo ${{ steps.api.outputs.headers }}          
