on:
  rss:
    url: https://hnrss.org/newest
    config:
      limit: 1
      active: true
      every: "30 6 */2 * *"
jobs:
  prochoice:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=wotag::$(date +'%A')"
    - name: Translate current date
      id: translate
      run: |
        if [ "${{steps.date.outputs.wotag}}" = "Monday" ]
        then
          echo "::set-output name=wotag::Montag"
        elif [ "${{steps.date.outputs.wotag}}" = "Tuesday" ]
        then
          echo "::set-output name=wotag::Dienstag"
        elif [ "${{steps.date.outputs.wotag}}" = "Wednesday" ]
        then
          echo "::set-output name=wotag::Mittwoch"
        elif [ "${{steps.date.outputs.wotag}}" = "Thursday" ]
        then
          echo "::set-output name=wotag::Donnerstag"
        elif [ "${{steps.date.outputs.wotag}}" = "Friday" ]
        then
          echo "::set-output name=wotag::Freitag"
        elif [ "${{steps.date.outputs.wotag}}" = "Saturday" ]
        then
          echo "::set-output name=wotag::Samstag"
        elif [ "${{steps.date.outputs.wotag}}" = "Sunday" ]
        then
          echo "::set-output name=wotag::Sonntag"
        else
          echo "::set-output name=wotag::Arbeitstag"
        fi
    - name: 'Call friendica API'
      uses: actionsflow/axios@v1
      with:
        url: https://libranet.de/api/statuses/update.json
        method: 'POST'
        accept: 200,201,204,429
        headers: '{ "Content-Type": "application/json" }'
        data: '{ "source": "Tusky",  "title": "Auch heute am <<<${{steps.translate.outputs.wotag}}>>>",  "htmlstatus": "werden wieder rund 275 Kinder in Deutschland getötet werden. 96% davon auf Wunsch der Eltern. #prochoice #Ableismus #Misogynie" }'
        params: '{ "source": "Tusky",  "title": "Auch heute am <<<${{steps.translate.outputs.wotag}}>>>",  "htmlstatus": "werden wieder rund 275 Kinder in Deutschland getötet werden. 96% davon auf Wunsch der Eltern. #prochoice #Ableismus #Misogynie" }'
        timeout: 10000
        basic-auth: ${{ secrets.friendica_auth_username }}:${{ secrets.friendica_auth_password }}
        is_debug: true
