on:
  rss:
    url: https://hnrss.org/newest
    config:
      limit: 1
      active: true
      every: "30 6 */4 * 1-5"
jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=wotag::$(date +'%A')"
    - name: Translate current date
      id: translate
      run: |
        if [ "${{steps.date.outputs.wotag}}" = "Monday" ]
        then
          echo "::set-output name=wotag::Montag"
        elif [ "${{steps.date.outputs.wotag}}" = "Tuesday" ]
        then
          echo "::set-output name=wotag::Dienstag"
        elif [ "${{steps.date.outputs.wotag}}" = "Wednesday" ]
        then
          echo "::set-output name=wotag::Mittwoch"
        elif [ "${{steps.date.outputs.wotag}}" = "Thursday" ]
        then
          echo "::set-output name=wotag::Donnerstag"
        elif [ "${{steps.date.outputs.wotag}}" = "Friday" ]
        then
          echo "::set-output name=wotag::Freitag"
        elif [ "${{steps.date.outputs.wotag}}" = "Saturday" ]
        then
          echo "::set-output name=wotag::Samstag"
        elif [ "${{steps.date.outputs.wotag}}" = "Sunday" ]
        then
          echo "::set-output name=wotag::Sonntag"
        else
          echo "::set-output name=wotag::Arbeitstag"
        fi
    - name: 'Call fediverse'
      uses: rzr/fediverse-action@master
      with:
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN_PROCHOICE }}
        message: |
            Auch heute am ${{steps.translate.outputs.wotag}} werden wieder rund 275 Kinder in Deutschland getötet worden sein.
            264 Kinder auf Wunsch der Eltern.
            #prochoice #Ableismus #Misogynie
        host: "muenchen.social"
    - name: Print Wochentag
      env:
        wochentag: ${{steps.translate.outputs.wotag}}
      run: |
        echo ProChoiceStatement Wochentag: $wochentag
