on:
  rss:
    url: https://hnrss.org/newest
    config:
      limit: 1
      active: true
      every: "30 8 * 1,3,5,6,7 *"
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: statement2twitter
        uses: ethomson/send-tweet-action@v1
        with:
          status: |
              Der Begriff Schwangerschaftsabbruch ist irreführend.
              Es ist ein Lebensabbruch.
              So wie jede Tötung.
              #prochoice #Abtreibung #wegmit218 #wegmit219a
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
