on:
  rss:
    url: https://hnrss.org/newest
    config:
      limit: 1
      active: true
      every: "0 11 */4 * *"
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: 'Call fediverse'
      uses: rzr/fediverse-action@master
      with:
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN_PROCHOICE }}
        message: |
            Art. 1 GG
            (1) Die Würde des Menschen ist unantastbar. [...].
            (2) Das Deutsche Volk bekennt sich darum zu unverletzlichen und unveräußerlichen Menschenrechten als Grundlage {...].
            (3) Die nachfolgenden Grundrechte binden Gesetzgebung, vollziehende Gewalt und Rechtsprechung als unmittelbar geltendes Recht.
            Die Zugehörigkeit zur Spezies Mensch ist unabhängig vom Alter.
            Was diskutiert Ihr noch?
            #prochoice #wegmit218 #wegmit219a
        host: "muenchen.social"
