on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "30 8,12 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: PSALMUS
jobs:
  tgram:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Get textstelle
        id: kapitel
        run: echo "::set-output name=stelle::"$(echo "${{on.rss.outputs.title}}" | awk -F" " '{print $NF}')
      - name: Get buch
        id: buch
        run: |
          if [[ "${{on.rss.outputs.title}}" == *"ps"* ]]
          then
            echo "::set-output name=name::ps"
          elif [[ "${{on.rss.outputs.title}}" == *"Genesis"* ]]
          then
            echo "::set-output name=name::1.Mose"
          elif [[ "${{on.rss.outputs.title}}" == *"Exodus"* ]]
          then
            echo "::set-output name=name::2.Mose"
          elif [[ "${{on.rss.outputs.title}}" == *"Leviticus"* ]]
          then
            echo "::set-output name=name::3.Mose"
          elif [[ "${{on.rss.outputs.title}}" == *"Numeri"* ]]
          then
            echo "::set-output name=name::4.Mose"
          elif [[ "${{on.rss.outputs.title}}" == *"Deuteronomium"* ]]
          then
            echo "::set-output name=name::5.Mose"
          else
            echo "::set-output name=name::#Fehler"
          fi 
      - name: Get link
        id: link
        run: echo "::set-output name=url::https://www.bibleserver.com/EU/${{steps.buch.outputs.name}}${{steps.kapitel.outputs.stelle}}"
      - name: send titel message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{on.rss.outputs.title}}
              (${{steps.link.outputs.url}})
      - name: send inhalt message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              
              ${{on.rss.outputs.content}}
              
      - name: send fuss message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              --
              Quelle: ${{on.rss.outputs.link}}
              
              ----------
