on:
  rss:
    url:
      - https://www.vaticannews.va/de.rss.xml
      - https://www.katholisch.de/aktuelles/aktuelle-artikel.rss
#     - https://www.kath.net/ticker/index.xml
      - http://feeds.feedburner.com/kathnews-redaktion
      - https://www.kath.ch/feed/
      - https://www.blogs-kath.ch/feed/
      - https://righttolife.org.uk/feed
    config:
      limit: 999
jobs:
  send2matrix:
     runs-on: ubuntu-latest
     steps:
       - name: send message
         uses: s3krit/matrix-message-action@v0.0.3
         with:
           room_id: ${{ secrets.MATRIX_NEWSROOM_ID }}
           access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
           message: ${{on.rss.outputs.content}} ${{on.rss.outputs.link}}
           server: "synod.im"
