on:
  rss:
    url:
      - https://www.vaticannews.va/de.rss.xml # wird ungünstig formatiert, deswegen auskommentiert.
      - https://www.katholisch.de/aktuelles/aktuelle-artikel.rss
      - https://www.kath.net/ticker/index.xml
      - http://feeds.feedburner.com/kathnews-redaktion
      - https://www.kath.ch/feed/
      - https://www.blogs-kath.ch/feed/
      - https://righttolife.org.uk/feed
    config:
      format: |
        item.content = item.content.replace(/<style([\s\S]*?)<\/style>/gi, '').replace(/<script([\s\S]*?)<\/script>/gi, '').replace(/<\/div>/ig, '').replace(/<\/li>/ig, '').replace(/<li>/ig, '').replace(/<\/ul>/ig, '').replace(/<\/p>/ig, '').replace(/<br\s*[\/]?>/gi, '').replace(/<[^>]+>/ig, '').replace(/<\/*code>/ig, '').replace(/<\/*textarea.*>/ig, '').replace(/<\/*samp.*>/ig, '').replace(/<\/*pre.*>/ig, '')
        return item;
#      limit: 999
jobs:
  send2matrix:
     runs-on: ubuntu-latest
     steps:
       - name: send message
         uses: s3krit/matrix-message-action@v0.0.3
         with:
           room_id: ${{ secrets.MATRIX_NEWSROOM_ID }}
           access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
           message: |
             <p><br>
#             ${{on.rss.outputs.title}}
             <p>${{on.rss.outputs.content}}</p>
             
             <a href="${{on.rss.outputs.link}}">${{on.rss.outputs.link}}</a>
             <br><br></p>
           server: "synod.im"
