on:
  rss:
    url:
      - https://www.vaticannews.va/de.rss.xml
      - https://www.katholisch.de/aktuelles/aktuelle-artikel.rss
      - https://www.kath.net/ticker/index.xml
      - http://feeds.feedburner.com/kathnews-redaktion
      - https://www.kath.ch/feed/
      - https://www.blogs-kath.ch/feed/
      - https://righttolife.org.uk/feed
      - https://www.alfa-ev.de/feed/
      - https://www.bundesverband-lebensrecht.de/feed/
#      - https://www.die-tagespost.de/rss-feed/
      - https://www.domradio.de/rss-feeds/domradio-rss.xml
      - https://feeds.feedburner.com/cnadeutsche/nachrichten
    config:
      format: |
        item.content = item.content.replace(/<style([\s\S]*?)<\/style>/gi, '').replace(/<script([\s\S]*?)<\/script>/gi, '').replace(/<\/div>/ig, '').replace(/<\/li>/ig, '').replace(/<li>/ig, '').replace(/<\/ul>/ig, '').replace(/<\/p>/ig, '').replace(/<br\s*[\/]?>/gi, '').replace(/<[^>]+>/ig, '').replace(/<\/*code>/ig, '').replace(/<\/*textarea.*>/ig, '').replace(/<\/*samp.*>/ig, '').replace(/<\/*pre.*>/ig, '')
        return item;
#      limit: 999
jobs:
  send2matrix:
     runs-on: ubuntu-latest
     steps:
       - name: send message
         uses: s3krit/matrix-message-action@v0.0.3
         with:
           room_id: ${{ secrets.MATRIX_NEWSROOM_ID }}
           access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
           message: |
             <p><br>
             <p>${{on.rss.outputs.title}}</p>
             <p>${{on.rss.outputs.content}}</p>
             
             <a href="${{on.rss.outputs.link}}">${{on.rss.outputs.link}}</a>
             <br><br></p>
           server: "synod.im"
  send2slack:
     runs-on: ubuntu-latest
     steps:
       - name: Notify slack
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
         uses: pullreminders/slack-action@master
         with:
           args: '{\"channel\":\"C02KL39HTE0\",\"text\":\"<${{on.rss.outputs.link}}|${{on.rss.outputs.link}}>\"}'
  send2discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_NACHRICHTEN }}
#          DISCORD_EMBEDS: {"embeds": [{"title": "${{on.rss.outputs.title}}", "url": "${{on.rss.outputs.link}}", "description": "${{on.rss.outputs.content}}"}]}
        uses: Ilshidur/action-discord@master
        with:
          args: '${{on.rss.outputs.content}}'
