on:
  rss:
    url: https://www.die-tagespost.de/storage/rss/rss/die-tagespost-komplett.xml
    config:
      active: true
      filter:
        content:
          $regex: ....+
        title:
          $regex: ....+
        link:
          $regex: ....+
      format: |
        item.title = item.title.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&auml;/g, 'ä').replace(/&ouml;/g, 'ö').replace(/&uuml;/g, 'ü').replace(/&szlig;/g, 'ß').replace(/&bdquo;/g, '„').replace(/&ldquo;/g, '“').replace(/&nbsp;/g, ' ').replace(/&ndash;/g, '-')
        return item;
jobs:
  post2tumblr:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/ifttt-webhook-action@v1
        with:
          event: post2tumblr
          key: ${{ secrets.TUMBLR_WEBHOOK_KEY }}
          value1: ${{ on.rss.outputs.title }}
          value2: "${{ on.rss.outputs.content }} </br> ${{on.rss.outputs.link}}"
          value3: "Die Tagespost"
