on:
  rss:
    url: https://www.vaticannews.va/de.rss.xml
jobs:
  post2tumblr:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.TUMBLR_WEBHOOK_URL }}
          method: POST
          body: |
            {
              "value1": "<<<${{ on.rss.outputs.title }}>>>",
              "value2": "<<<${{ on.rss.outputs.content }}>>>",
              "value3": "Vatican News"
            }
