on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: vaticannews_de
      exclude_replies: true
      include_rts: true
      tweet_mode: "extended"
    config:
      active: true
      filter:
        full_text:
          $regex: ....+
        created_at:
          $regex: ....+
      format: |
        item.full_text = item.full_text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&auml;/g, 'ä').replace(/&ouml;/g, 'ö').replace(/&uuml;/g, 'ü').replace(/&szlig;/g, 'ß').replace(/&bdquo;/g, '„').replace(/&ldquo;/g, '“').replace(/&nbsp;/g, ' ').replace(/&ndash;/g, '-')
        return item;
jobs:
  send2matrix:
     runs-on: ubuntu-latest
     steps:
       - name: send message
         uses: s3krit/matrix-message-action@v0.0.3
         with:
           room_id: ${{ secrets.MATRIX_NEWSROOM_ID }}
           access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
           message: ${{ on.twitter.outputs.full_text }} ${{ on.twitter.outputs.entities.0.urls }}
           server: "synod.im"
