on:
  youtube:
    channel_id:
      - UC-WCY1iPwdVDokbkV2q0zPQ
      - UCZV9O-fJvZcJMlQFd7K4O2w
      - UCMbQQLYvzvCvJsyYA60HIOg
      - UCAYVrIie91PGEtbzLrQeReg
jobs:
  fediverse-mastodon:
    name: send2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: 'Call fediverse'
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          message: "${{on.youtube.outputs.title}} ${{on.youtube.outputs.link}}"
          host: "muenchen.social" # If not using default "mastodon.social"
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{on.youtube.outputs.title}}  ${{on.youtube.outputs.link}}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{secrets.EMAIL_SERVER_ADDRESS}}
          server_port: ${{secrets.EMAIL_SERVER_PORT}}
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: |
            ${{on.youtube.outputs.title}}
            ${{on.youtube.outputs.description}}
            ${{on.youtube.outputs.link}}
          # Read file contents as body:
          to: ${{secrets.EMAIL_TO_LFA}}
          from: ${{secrets.EMAIL_FROM}}
          # Optional content type (defaults to text/plain):
          content_type: text/html
  video2tumblr:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/ifttt-webhook-action@v1
        with:
          event: video2tumblr
          key: ${{ secrets.TUMBLR_WEBHOOK_KEY }}
          value1: ${{on.youtube.outputs.link}}
          value2: ${{on.youtube.outputs.description}}
          value3: "YouTube Videos"
