on:
  youtube:
    channel_id:
      - UC-WCY1iPwdVDokbkV2q0zPQ
      - UCZV9O-fJvZcJMlQFd7K4O2w
    config:
      limit: 1
jobs:
  fediverse-mastodon:
    name: send2mastodon
    runs-on: ubuntu-latest
    steps:
      - name: 'Call fediverse'
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          message: "${{on.youtube.outputs.description}}  ${{on.youtube.outputs.link}}"
          host: "muenchen.social" # If not using default "mastodon.social"
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{on.youtube.outputs.description}}  ${{on.youtube.outputs.link}}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
