on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: sakrumverum
      exclude_replies: true
      include_rts: true
    config:
      active: false
      every: "0 */1 * * *"
      limit: 1
      filter:
        full_text:
          $regex: ....+
        created_at:
          $regex: ....+
      format: |
        item.full_text = item.full_text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&auml;/g, 'ä').replace(/&ouml;/g, 'ö').replace(/&uuml;/g, 'ü').replace(/&szlig;/g, 'ß').replace(/&bdquo;/g, '„').replace(/&ldquo;/g, '“').replace(/&nbsp;/g, ' ').replace(/&ndash;/g, '-')
        return item;
jobs:
  post2tumblr:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.TUMBLR_WEBHOOK_URL }}
          method: POST
          body: |
            {
              "value1": "<<<${{ on.twitter.outputs.full_text }}>>>",
              "value2": "<p><i><a href=\"https:\/\/twitter.com\/${{ on.twitter.outputs.user.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}\">https:\/\/twitter.com\/${{ on.twitter.outputs.screen_name }}\/status\/${{ on.twitter.outputs.id_str }}</a></i><\/p><br><p>${{ on.twitter.outputs.created_at }}<\/p>",
              "value3": "twitter"
            }
